#31: Improve stability when deleting files
exasol/small-json-files-test-fixture pull request #32
Opened 2024-01-22 12:53 UTC by kaklakariada

Closes #31

2024-01-22 16:57 UTC, ckunki requested changes

2024-01-22 16:57 UTC, ckunki commented on pom.xml
> +                    <filesets>
Here I would need some explanation.

2024-01-22 16:57 UTC, ckunki commented on src/main/resources/createJsonFilesLambda/createJsonFilesLambda.js
Also for this file I would appreciate a short explanation / introduction.

2024-01-23 15:37 UTC, ckunki approved these changes

2024-01-23 15:37 UTC, ckunki commented on src/main/resources/createJsonFilesLambda/createJsonFilesLambda.js
> +    return doWithRetry(`Upload file ${key}`, async function upload() {
Could this be an anonymous function?

2024-01-23 15:40 UTC, kaklakariada commented on src/main/resources/createJsonFilesLambda/createJsonFilesLambda.js
> +    return doWithRetry(`Upload file ${key}`, async function upload() {
Sorry, won't fix

2024-01-23 15:40 UTC, merged